"""Add Agent and Site tables with indexes

Revision ID: 0adae4f81bca
Revises: 14eb81de542b
Create Date: 2025-08-11 08:04:17.424223

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0adae4f81bca'
down_revision = '14eb81de542b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_articles_submitted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('api_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('default_category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('default_tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('health_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_posts_published', sa.Integer(), nullable=False),
    sa.Column('connection_timeout', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 创建性能优化索引
    # Articles表的多代理和多站点查询索引
    op.create_index('idx_articles_submitting_agent', 'articles', ['submitting_agent_id'], 
                    postgresql_where=sa.text('submitting_agent_id IS NOT NULL'))
    op.create_index('idx_articles_target_site', 'articles', ['target_site_id'], 
                    postgresql_where=sa.text('target_site_id IS NOT NULL'))
    op.create_index('idx_articles_agent_status', 'articles', ['submitting_agent_id', 'status'], 
                    postgresql_where=sa.text('submitting_agent_id IS NOT NULL'))
    op.create_index('idx_articles_site_status', 'articles', ['target_site_id', 'status'], 
                    postgresql_where=sa.text('target_site_id IS NOT NULL'))
    op.create_index('idx_articles_status_updated_agent', 'articles', ['status', 'updated_at', 'submitting_agent_id'])
    
    # Agents表索引
    op.create_index('idx_agents_active', 'agents', ['is_active'])
    op.create_index('idx_agents_role', 'agents', ['role'])
    op.create_index('idx_agents_last_seen', 'agents', ['last_seen'])
    
    # Sites表索引
    op.create_index('idx_sites_active', 'sites', ['is_active'])
    op.create_index('idx_sites_health_status', 'sites', ['health_status'])
    op.create_index('idx_sites_last_health_check', 'sites', ['last_health_check'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除索引
    op.drop_index('idx_sites_last_health_check')
    op.drop_index('idx_sites_health_status') 
    op.drop_index('idx_sites_active')
    op.drop_index('idx_agents_last_seen')
    op.drop_index('idx_agents_role')
    op.drop_index('idx_agents_active')
    op.drop_index('idx_articles_status_updated_agent')
    op.drop_index('idx_articles_site_status')
    op.drop_index('idx_articles_agent_status')
    op.drop_index('idx_articles_target_site')
    op.drop_index('idx_articles_submitting_agent')
    
    # 删除表
    op.drop_table('sites')
    op.drop_table('agents')
    # ### end Alembic commands ###