"""Add Agent and Site models for v2.1

Revision ID: 14eb81de542b
Revises: 
Create Date: 2025-08-11 08:03:17.551791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14eb81de542b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('submitting_agent_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('articles', sa.Column('submitting_agent_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('articles', sa.Column('agent_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('articles', sa.Column('target_site_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('articles', sa.Column('target_site_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('articles', sa.Column('publishing_agent_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.alter_column('articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('articles', 'publishing_agent_id')
    op.drop_column('articles', 'target_site_name')
    op.drop_column('articles', 'target_site_id')
    op.drop_column('articles', 'agent_metadata')
    op.drop_column('articles', 'submitting_agent_name')
    op.drop_column('articles', 'submitting_agent_id')
    # ### end Alembic commands ###