"""Fix api_key_display nullable constraint

Revision ID: 4ab0d0f15b57
Revises: 5002e3dbc60a
Create Date: 2025-08-18 15:09:38.035387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab0d0f15b57'
down_revision = '5002e3dbc60a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 将 api_key_display 字段改为允许 null，并设置默认值
    op.alter_column('agents', 'api_key_display', nullable=True)
    op.alter_column('agents', 'api_key_display', server_default='')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚：移除默认值并改回非空
    op.alter_column('agents', 'api_key_display', server_default=None)
    op.alter_column('agents', 'api_key_display', nullable=False)
    # ### end Alembic commands ###