"""Add api_key_display field to agents table

Revision ID: 5002e3dbc60a
Revises: a670b164056c
Create Date: 2025-08-18 14:18:50.114084

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5002e3dbc60a'
down_revision = 'a670b164056c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加字段，先允许为null
    op.add_column('agents', sa.Column('api_key_display', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    
    # 为现有记录生成掩码（基于现有数据的前后8位模式）
    # 由于我们无法从哈希值还原原始key，先设置一个占位符
    op.execute("UPDATE agents SET api_key_display = '****************************************' WHERE api_key_display IS NULL")
    
    # 现在将字段设为非空
    op.alter_column('agents', 'api_key_display', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'api_key_display')
    # ### end Alembic commands ###