"""扩展Agent和Site模型支持完整配置

Revision ID: 9dfe43a9ebd7
Revises: 0adae4f81bca
Create Date: 2025-08-12 21:14:22.249125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9dfe43a9ebd7'
down_revision = '0adae4f81bca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('agents', sa.Column('rate_limit', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('permissions', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('notifications', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('total_articles_published', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('total_articles_rejected', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('first_submission', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('last_submission', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_agents_active'), table_name='agents')
    op.drop_index(op.f('idx_agents_last_seen'), table_name='agents')
    op.drop_index(op.f('idx_agents_role'), table_name='agents')
    op.drop_column('agents', 'is_active')
    op.drop_column('agents', 'role')
    op.add_column('articles', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('wordpress_permalink', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('reviewer_notes', sa.Text(), nullable=True))
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('articles', 'content_markdown',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('articles', 'publish_error_message',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('articles', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_articles_agent_status'), table_name='articles', postgresql_where='(submitting_agent_id IS NOT NULL)')
    op.drop_index(op.f('idx_articles_site_status'), table_name='articles', postgresql_where='(target_site_id IS NOT NULL)')
    op.drop_index(op.f('idx_articles_status_updated_agent'), table_name='articles')
    op.drop_index(op.f('idx_articles_submitting_agent'), table_name='articles', postgresql_where='(submitting_agent_id IS NOT NULL)')
    op.drop_index(op.f('idx_articles_target_site'), table_name='articles', postgresql_where='(target_site_id IS NOT NULL)')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_submitted_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_submitted_by'), table_name='articles')
    op.drop_column('articles', 'reviewed_at')
    op.drop_column('articles', 'published_at')
    op.drop_column('articles', 'reviewed_by')
    op.drop_column('articles', 'wordpress_url')
    op.drop_column('articles', 'submitted_by')
    op.drop_column('articles', 'submitted_at')
    op.add_column('sites', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('sites', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('sites', sa.Column('wordpress_config', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('publishing_rules', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('rate_limit', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('notifications', sa.JSON(), nullable=True))
    op.add_column('sites', sa.Column('total_posts_failed', sa.Integer(), nullable=False))
    op.add_column('sites', sa.Column('last_publish', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_sites_active'), table_name='sites')
    op.drop_index(op.f('idx_sites_health_status'), table_name='sites')
    op.drop_index(op.f('idx_sites_last_health_check'), table_name='sites')
    op.drop_column('sites', 'default_tags')
    op.drop_column('sites', 'api_url')
    op.drop_column('sites', 'is_active')
    op.drop_column('sites', 'username')
    op.drop_column('sites', 'default_category')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_reviewer', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'is_reviewer')
    op.drop_column('users', 'password_hash')
    op.add_column('sites', sa.Column('default_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sites', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('sites', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('sites', sa.Column('api_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sites', sa.Column('default_tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_sites_last_health_check'), 'sites', ['last_health_check'], unique=False)
    op.create_index(op.f('idx_sites_health_status'), 'sites', ['health_status'], unique=False)
    op.create_index(op.f('idx_sites_active'), 'sites', ['is_active'], unique=False)
    op.drop_column('sites', 'last_publish')
    op.drop_column('sites', 'total_posts_failed')
    op.drop_column('sites', 'notifications')
    op.drop_column('sites', 'rate_limit')
    op.drop_column('sites', 'publishing_rules')
    op.drop_column('sites', 'wordpress_config')
    op.drop_column('sites', 'status')
    op.drop_column('sites', 'description')
    op.add_column('articles', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('submitted_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('wordpress_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_articles_submitted_by'), 'articles', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_articles_submitted_at'), 'articles', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index(op.f('idx_articles_target_site'), 'articles', ['target_site_id'], unique=False, postgresql_where='(target_site_id IS NOT NULL)')
    op.create_index(op.f('idx_articles_submitting_agent'), 'articles', ['submitting_agent_id'], unique=False, postgresql_where='(submitting_agent_id IS NOT NULL)')
    op.create_index(op.f('idx_articles_status_updated_agent'), 'articles', ['status', 'updated_at', 'submitting_agent_id'], unique=False)
    op.create_index(op.f('idx_articles_site_status'), 'articles', ['target_site_id', 'status'], unique=False, postgresql_where='(target_site_id IS NOT NULL)')
    op.create_index(op.f('idx_articles_agent_status'), 'articles', ['submitting_agent_id', 'status'], unique=False, postgresql_where='(submitting_agent_id IS NOT NULL)')
    op.alter_column('articles', 'rejection_reason',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'publish_error_message',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'content_markdown',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('articles', 'reviewer_notes')
    op.drop_column('articles', 'wordpress_permalink')
    op.drop_column('articles', 'content_html')
    op.add_column('agents', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_agents_role'), 'agents', ['role'], unique=False)
    op.create_index(op.f('idx_agents_last_seen'), 'agents', ['last_seen'], unique=False)
    op.create_index(op.f('idx_agents_active'), 'agents', ['is_active'], unique=False)
    op.drop_column('agents', 'last_submission')
    op.drop_column('agents', 'first_submission')
    op.drop_column('agents', 'total_articles_rejected')
    op.drop_column('agents', 'total_articles_published')
    op.drop_column('agents', 'notifications')
    op.drop_column('agents', 'permissions')
    op.drop_column('agents', 'rate_limit')
    op.drop_column('agents', 'status')
    # ### end Alembic commands ###