"""Add role templates and agent role extensions

Revision ID: a670b164056c
Revises: d485143b22a0
Create Date: 2025-08-15 18:25:28.862798

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a670b164056c'
down_revision = 'd485143b22a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('quota_limits', sa.JSON(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_template_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_template_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('old_config', sa.JSON(), nullable=True),
    sa.Column('new_config', sa.JSON(), nullable=True),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_template_id'], ['role_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('role_template_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('agents', sa.Column('permissions_override', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'agents', 'role_templates', ['role_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'permissions_override')
    op.drop_column('agents', 'role_template_id')
    op.drop_table('role_template_history')
    op.drop_table('role_templates')
    # ### end Alembic commands ###