"""扩展Agent权限配置支持审批发布功能

Revision ID: d485143b22a0
Revises: e669629e2396
Create Date: 2025-08-15 11:37:33.125020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd485143b22a0'
down_revision = 'e669629e2396'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###