"""添加approved状态到ArticleStatus枚举

Revision ID: e669629e2396
Revises: 1b4ddf359d52
Create Date: 2025-08-15 11:28:06.077475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'e669629e2396'
down_revision = '1b4ddf359d52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 添加approved状态到ArticleStatus枚举
    op.execute("ALTER TYPE articlestatus ADD VALUE 'approved' AFTER 'pending_review'")
    
    op.alter_column('articles', 'content_markdown',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('articles', 'content_html',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('articles', 'status',
               existing_type=postgresql.ENUM('pending_review', 'publishing', 'published', 'publish_failed', 'rejected', name='articlestatus'),
               nullable=True)
    op.alter_column('articles', 'publish_error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('articles', 'reviewer_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('articles', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'rejection_reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'reviewer_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'publish_error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'status',
               existing_type=postgresql.ENUM('pending_review', 'publishing', 'published', 'publish_failed', 'rejected', name='articlestatus'),
               nullable=False)
    op.alter_column('articles', 'content_html',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('articles', 'content_markdown',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###