# Multi-Agent Configuration for MCP WordPress Publisher v2.1
# This file defines multiple AI agents that can submit articles for publishing

# Global agent settings
global_settings:
  # Default rate limiting per agent
  default_rate_limit:
    requests_per_minute: 10
    requests_per_hour: 100
    requests_per_day: 500
  
  # Default timeout settings
  default_timeouts:
    submission_timeout: 30  # seconds
    approval_timeout: 300   # seconds
  
  # Security settings
  security:
    require_api_key: true
    enable_ip_whitelist: false
    session_timeout: 3600  # seconds
    max_failed_attempts: 5
    lockout_duration: 900  # seconds (15 minutes)

# Individual agent configurations
agents: []

# Agent groups (for easier management)
agent_groups: {}

# Monitoring and alerting
monitoring:
  # Alert thresholds
  alert_on_failed_submissions: 5  # per agent per hour
  alert_on_high_rejection_rate: 50  # percentage
  alert_on_agent_lockout: true
  
  # Metrics collection
  collect_metrics: true
  metrics_retention_days: 90
  
  # Health check intervals
  health_check_interval: 300  # seconds (5 minutes)
  
# Audit settings
audit:
  log_all_actions: true
  log_sensitive_data: false
  retention_days: 365
  export_format: "json"