# Logging Configuration for MCP WordPress Publisher v2.1
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'
    datefmt: '%Y-%m-%dT%H:%M:%SZ'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /app/logs/mcp-wordpress.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: /app/logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  audit_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /app/logs/audit.log
    maxBytes: 10485760  # 10MB
    backupCount: 10

loggers:
  mcp_wordpress:
    level: INFO
    handlers: [console, file]
    propagate: false

  mcp_wordpress.auth:
    level: INFO
    handlers: [console, file, audit_file]
    propagate: false

  mcp_wordpress.tools:
    level: INFO
    handlers: [console, file, audit_file]
    propagate: false

  sqlalchemy.engine:
    level: WARNING
    handlers: [console, file]
    propagate: false

  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [console, error_file]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]