# Multi-Site Configuration for MCP WordPress Publisher v2.1
# This file defines multiple WordPress sites for content publishing

# Global site settings
global_settings:
  # Default timeout settings for all sites
  default_timeouts:
    connection_timeout: 30  # seconds
    read_timeout: 60       # seconds
    publish_timeout: 120   # seconds
  
  # Default retry settings
  default_retry:
    max_attempts: 3
    retry_delay: 5  # seconds
    backoff_multiplier: 2
  
  # Health check settings
  health_check:
    interval: 300  # seconds (5 minutes)
    timeout: 10    # seconds
    retry_attempts: 3
  
  # Security settings
  security:
    verify_ssl: true
    require_https: true
    user_agent: "MCP WordPress Publisher v2.1"

# Individual site configurations
sites: []

# Site groups (for easier management)
site_groups: {}

# Load balancing and failover
load_balancing:
  # Strategy: round_robin, priority, least_connections
  strategy: "priority"
  
  # Failover settings
  enable_failover: true
  failover_threshold: 3  # failures before switching
  failover_cooldown: 300  # seconds before retry

# Monitoring and health checks
monitoring:
  # Health check settings
  health_check_interval: 300  # seconds
  health_check_timeout: 10    # seconds
  
  # Alert thresholds
  alert_on_site_down: true
  alert_on_high_failure_rate: 20  # percentage
  alert_on_slow_response: 30      # seconds
  
  # Metrics collection
  collect_performance_metrics: true
  metrics_retention_days: 90

# Backup and recovery
backup:
  # Backup published content metadata
  backup_published_content: true
  backup_interval: "daily"
  backup_retention_days: 30
  backup_location: "/app/backups"

# Content synchronization
synchronization:
  # Enable cross-site content sync
  enable_cross_site_sync: false
  sync_categories: true
  sync_tags: true
  
  # Duplicate detection
  detect_duplicates: true
  duplicate_threshold: 0.85  # similarity threshold